### ISSUE TITLE
Drive OAuth client secret

### ISSUE THREAD

**Issue by cry** [NSBHS-Programming-Club/nsbhsProgClub#5]
Don't store your client secret in a public git file.

Read https://git-scm.com/docs/gitignore and learn how to use.

Also, check your drive:
```
root@testserver:~# rclone ls drive:/
  1560010 Getting started
       32 ./wow_such_drive.txt
```

**Comment by Varun-Sethu** [comment]
Yeah, i have to delete that, we are not using the drive api.
